### ISSUE TITLE
Variables not considered in version specification?

### ISSUE THREAD

**Issue by rhaschke** [RDTK/generator#19]
build-generator version: 0.27.56

I was trying to use a variable in version specifications for projects in a distribution, like this:

```yaml
variables:
  ros: ${next-value|melodic}
versions:
- xmlrpcpp @${ros}-devel
```

The final value of the variable was passed from cmdline via `-D ros=kinetic`.
While `--track-variable` correctly reports kinetic as the used variable, the build-job-names generated, still show melodic (from the distribution default).
