### ISSUE TITLE
New tag "groups" to allow scoping of variables within a single file

### ISSUE THREAD

**Issue by rhaschke** [RDTK/generator#28]
As discussed in today's meeting, it would be great to have a `groups` tag in `distribution` files:

```yaml
variables:
  foo: bar

groups:
  - variables:
      foo: foo
    includes:
    projects:

  - variables:
      foo: foo
    includes:
    projects:

includes:
  name: foo
  parameters:
    foo: foobar

projects:
```
Whether or not the groups tag should be hierarchical, i.e. allow groups below groups, is to be decided on the effort to implement this feature :wink:
