### ISSUE TITLE
Allow sub-directories for all recipe kinds

### ISSUE THREAD

**Issue by scymtym** [RDTK/generator#33]
**Is your feature request related to a problem? Please describe.**

It is sometimes convenient to place recipe files in sub-directories below the type-specific directories `projects`, `templates`, etc. This is not currently well supported.

**Describe the solution you'd like**

References to recipes in sub-directories such as

```yaml
include:
  - sub-directory/name

versions:
  - sub-directory/name@version
```

in distribution recipes or

```yaml
inherit:
  - sub-directory/name
```

in template recipes should work.

Note that this may lead to problems for project recipes since artifact names derived from project names (e.g. Jenkins job names, catalog file names, report file names) can now contain `/` characters.
