### ISSUE TITLE
Improve dependency install

### ISSUE THREAD

**Issue by LeroyR** [RDTK/generator#43]
**Is your feature request related to a problem? Please describe.**
Most distributions require adding the ROS ppa to install dependencies. This is nowhere documented after running generate.

Example: When I call the generator like this:
After calling
```sh
build-generator platform-requirements …
```
Most distributions(ROS) require adding of custom PPA which is documented nowhere

When I call the generator like this:
```sh
build-generator generate …
```
the output does not tell me that i *may* have to install dependencies

**Describe the solution you'd like**
- Add the possibility to define additional PPA+Keys that for a platform
- I would like it if the generator can prompt for the addition of PPAs defined within the distribution. Maybe after platform-requirements call?
- Add a generator-message variable to distributions where i can add custom messages after generate calls (default something along "Remember to run platform-requirements and install missing dependencies. "

**Comment by scymtym** [comment]
> Add the possibility to define additional PPA+Keys that for a platform

For the prototype docker stuff, I use the following:

```yaml
platform-requires:
  ubuntu:
    packages:
      - …
    keys:
      - http://packages.osrfoundation.org/gazebo.key
    repositories:
      - deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main
```
Is that close to what you mean?

> I would like it if the generator can prompt for the addition of PPAs defined within the distribution. Maybe after platform-requirements call?

What do you mean by "prompt"? And would the effect be?

> Add a generator-message variable to distributions where i can add custom messages after generate calls (default something along "Remember to run platform-requirements and install missing dependencies. "

Good idea. Please make a separate issue for this.
