### ISSUE TITLE
Double Space on list Expansion

### ISSUE THREAD

**Issue by LeroyR** [RDTK/generator#46]
**Which generator version are you using?**

```sh
build-generator 0.31.36
asdf            3.3.1
SBCL            1.5.5.0.sbcl-1.5.5.0-8ffc9ea
```

**What did you do?**

1. The relevant recipe looks like this

```yaml
templates:
  - runnable
  - base

variables:

  options:
    - FOO
    - BAR
    - BAZ

  options1: '${options} '
  options2: '${options}2'
  options3: '${options}  '

  shell.command: |
    @{options}
    @{generator.options}
    @{generator.options2}
    @{generator.options3}
```

Which doubles spaces for the jenkins shell:

```
FOOBARBAZ
FOO  BAR  BAZ  
FOO2BAR2BAZ2
FOO    BAR    BAZ    
```
