### ISSUE TITLE
Empty variable references set referencer NIL

### ISSUE THREAD

**Issue by LeroyR** [RDTK/generator#58]
**Which generator version are you using?**

```sh
build-generator 0.34.16
asdf            3.3.1
SBCL            2.1.8
```

**What did you do?**

1. Setting a variable to empty Strings `""` or `" "` makes variables that reference this NIL

   * `projects/broken.project`:

     ```yaml
     foo: 1
     bar: 2
     baz: |
       # foo 
       ${foo}
       # bar
       ${bar}
     ```

   * `distributions/broken.distribution`:

     ```yaml
     - name: broken
       version: master
       parameters:
         foo: ""
       …
     ```

  Same with empty string e.g. `" "`

**Which behavior did you expect?**
   ```yaml
baz: |
  # foo 
       
  # bar
  2
   ```

**What happened instead?**
```yaml
baz: NIL
```
